#!/bin/bash
source $HOME/.cache/wal/colors.sh
ALL_PATHS=""
IFS=:

for p in $PATH; do
    if [[ -d $p ]]; then
        ALL_PATHS+=$(find $p -executable -maxdepth 1 -printf "%f\n")
    fi
done

$(echo -e $ALL_PATHS | dmenu -fn 'xos4 Terminus:size=15' -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15")
