#!/bin/bash
pkill -f 'entr -p sh -c pkill -USR1 -x sxhkd'
pkill -f 'entr -p sh -c /home/llday/.config/bspwm/bspwmrc'
pkill -f 'entr -p sh -c xrdb /_ && source'

echo ~/.config/sxhkd/sxhkdrc | entr -p sh -c 'pkill -USR1 -x sxhkd' &
echo ~/.Xresources | entr -p sh -c 'xrdb /_ && source ~/.config/bspwm/bspwmrc' &

BSPWM_DIRS="$HOME/.config/bspwm/bspwmrc"
BSPWM_DIRS+="\n$HOME/.config/bspwm/autostart"
for f in $(ls ~/.config/polybar); do
    BSPWM_DIRS+="\n$HOME/.config/polybar/$f"
done

echo -e $BSPWM_DIRS | entr -p sh -c /home/llday/.config/bspwm/bspwmrc &
