config:
  backup: true
  banner: false
  create: true
  dotpath: .
  keepdot: false
  longkey: false
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  f_profile:
    src: profile
    dst: ~/.profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  f_autostart:
    src: config/bspwm/autostart
    dst: ~/.config/bspwm/autostart
  f_sxhkdrc:
    src: config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zprofile:
    src: config/zsh/.zprofile
    dst: ~/.config/zsh/.zprofile
  f_zshrc:
    src: config/zsh/.zshrc
    dst: ~/.config/zsh/.zshrc
  f_aliases:
    src: config/zsh/aliases
    dst: ~/.config/zsh/aliases
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_clang-format:
    src: clang-format
    dst: ~/.clang-format
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_dmenu_colored:
    src: Documents/scripts/dmenu_colored
    dst: ~/Documents/scripts/dmenu_colored
  f_update_edited:
    src: Documents/scripts/update_edited
    dst: ~/Documents/scripts/update_edited
  f_lfrc:
    src: config/lf/lfrc
    dst: ~/.config/lf/lfrc
  f_config.ini:
    src: config/polybar/config.ini
    dst: ~/.config/polybar/config.ini
  f_modules.ini:
    src: config/polybar/modules.ini
    dst: ~/.config/polybar/modules.ini
  f_bspwm_resize:
    src: Documents/scripts/bspwm_resize
    dst: ~/Documents/scripts/bspwm_resize
  f_euclid_mover:
    src: Documents/scripts/euclid_mover
    dst: ~/Documents/scripts/euclid_mover
  f_wallpaper_changer:
    src: Documents/scripts/wallpaper_changer
    dst: ~/Documents/scripts/wallpaper_changer
  f_windowpromoter:
    src: Documents/scripts/windowpromoter
    dst: ~/Documents/scripts/windowpromoter
  f_dmenu_open_app:
    src: Documents/scripts/dmenu_open_app
    dst: ~/Documents/scripts/dmenu_open_app
  f_dmenu_open_site:
    src: Documents/scripts/dmenu_open_site
    dst: ~/Documents/scripts/dmenu_open_site
  f_config:
    src: config/bat/config
    dst: ~/.config/bat/config
  f_fonts.conf:
    src: config/fontconfig/fonts.conf
    dst: ~/.config/fontconfig/fonts.conf
  f_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_colors.ini:
    src: config/polybar/colors.ini
    dst: ~/.config/polybar/colors.ini
  f_user_modules.ini:
    src: config/polybar/user_modules.ini
    dst: ~/.config/polybar/user_modules.ini
  f_bars.ini:
    src: config/polybar/bars.ini
    dst: ~/.config/polybar/bars.ini
  f_updates.sh:
    src: config/polybar/scripts/updates.sh
    dst: ~/.config/polybar/scripts/updates.sh
    chmod: '755'
  f_launch.sh:
    src: config/polybar/launch.sh
    dst: ~/.config/polybar/launch.sh
    chmod: '755'
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_bspwmrc:
    src: config/bspwm/bspwmrc
    dst: ~/.config/bspwm/bspwmrc
    chmod: '755'
  f_gitsigns.lua:
    src: config/nvim/lua/config/gitsigns.lua
    dst: ~/.config/nvim/lua/config/gitsigns.lua
  f_lualine.lua:
    src: config/nvim/lua/config/lualine.lua
    dst: ~/.config/nvim/lua/config/lualine.lua
  f_augroups.lua:
    src: config/nvim/lua/augroups.lua
    dst: ~/.config/nvim/lua/augroups.lua
  f_globals.lua:
    src: config/nvim/lua/globals.lua
    dst: ~/.config/nvim/lua/globals.lua
  f_keybindings.lua:
    src: config/nvim/lua/keybindings.lua
    dst: ~/.config/nvim/lua/keybindings.lua
  f_options.lua:
    src: config/nvim/lua/options.lua
    dst: ~/.config/nvim/lua/options.lua
  f_plugins.lua:
    src: config/nvim/lua/plugins.lua
    dst: ~/.config/nvim/lua/plugins.lua
  f_init.lua:
    src: config/nvim/init.lua
    dst: ~/.config/nvim/init.lua
  f_colors.lua:
    src: config/nvim/lua/config/colors.lua
    dst: ~/.config/nvim/lua/config/colors.lua
  f_indent_blankline.lua:
    src: config/nvim/lua/config/indent_blankline.lua
    dst: ~/.config/nvim/lua/config/indent_blankline.lua
  f_theme.lua:
    src: config/nvim/lua/config/theme.lua
    dst: ~/.config/nvim/lua/config/theme.lua
  f_treesitter.lua:
    src: config/nvim/lua/config/treesitter.lua
    dst: ~/.config/nvim/lua/config/treesitter.lua
  f_telescope.lua:
    src: config/nvim/lua/config/telescope.lua
    dst: ~/.config/nvim/lua/config/telescope.lua
  f_cmp.lua:
    src: config/nvim/lua/config/cmp.lua
    dst: ~/.config/nvim/lua/config/cmp.lua
  f_lsp.lua:
    src: config/nvim/lua/config/lsp.lua
    dst: ~/.config/nvim/lua/config/lsp.lua
  f_rust_analyzer.lua:
    src: config/nvim/lua/config/lsp/rust_analyzer.lua
    dst: ~/.config/nvim/lua/config/lsp/rust_analyzer.lua
  f_sumneko_lua.lua:
    src: config/nvim/lua/config/lsp/sumneko_lua.lua
    dst: ~/.config/nvim/lua/config/lsp/sumneko_lua.lua
  f_taplo.lua:
    src: config/nvim/lua/config/lsp/taplo.lua
    dst: ~/.config/nvim/lua/config/lsp/taplo.lua
  f_null-ls.lua:
    src: config/nvim/lua/config/null-ls.lua
    dst: ~/.config/nvim/lua/config/null-ls.lua
  f_trouble.lua:
    src: config/nvim/lua/config/trouble.lua
    dst: ~/.config/nvim/lua/config/trouble.lua
  f_luasnip.lua:
    src: config/nvim/lua/config/luasnip.lua
    dst: ~/.config/nvim/lua/config/luasnip.lua
  f_stylua.toml:
    src: config/stylua/stylua.toml
    dst: ~/.config/stylua/stylua.toml
profiles:
  arch:
    dotfiles:
    - f_profile
    - f_bashrc
    - f_xresources
    - f_picom.conf
    - f_autostart
    - f_sxhkdrc
    - f_zshenv
    - f_zprofile
    - f_zshrc
    - f_aliases
    - f_gitconfig
    - f_clang-format
    - f_xinitrc
    - f_dmenu_colored
    - f_update_edited
    - f_lfrc
    - f_config.ini
    - f_modules.ini
    - f_bspwm_resize
    - f_euclid_mover
    - f_wallpaper_changer
    - f_windowpromoter
    - f_dmenu_open_app
    - f_dmenu_open_site
    - f_config
    - f_fonts.conf
    - f_dunstrc
    - f_colors.ini
    - f_user_modules.ini
    - f_bars.ini
    - f_updates.sh
    - f_launch.sh
    - f_alacritty.yml
    - f_bspwmrc
    - f_gitsigns.lua
    - f_lualine.lua
    - f_augroups.lua
    - f_globals.lua
    - f_keybindings.lua
    - f_options.lua
    - f_plugins.lua
    - f_init.lua
    - f_colors.lua
    - f_indent_blankline.lua
    - f_theme.lua
    - f_treesitter.lua
    - f_telescope.lua
    - f_cmp.lua
    - f_lsp.lua
    - f_rust_analyzer.lua
    - f_sumneko_lua.lua
    - f_taplo.lua
    - f_null-ls.lua
    - f_trouble.lua
    - f_luasnip.lua
    - f_stylua.toml
