config:
  backup: true
  banner: false
  create: true
  dotpath: .
  keepdot: false
  longkey: false
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  f_profile:
    src: profile
    dst: ~/.profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  f_autostart:
    src: config/bspwm/autostart
    dst: ~/.config/bspwm/autostart
  f_bspwmrc:
    src: config/bspwm/bspwmrc
    dst: ~/.config/bspwm/bspwmrc
  f_sxhkdrc:
    src: config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zprofile:
    src: config/zsh/.zprofile
    dst: ~/.config/zsh/.zprofile
  f_zshrc:
    src: config/zsh/.zshrc
    dst: ~/.config/zsh/.zshrc
  f_aliases:
    src: config/zsh/aliases
    dst: ~/.config/zsh/aliases
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_clang-format:
    src: clang-format
    dst: ~/.clang-format
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_plugins.vim:
    src: config/nvim/vim-plug/plugins.vim
    dst: ~/.config/nvim/vim-plug/plugins.vim
  f_dmenu_run:
    src: Documents/scripts/dmenu_run
    dst: ~/Documents/scripts/dmenu_run
  f_update_edited:
    src: Documents/scripts/update_edited
    dst: ~/Documents/scripts/update_edited
  f_lfrc:
    src: config/lf/lfrc
    dst: ~/.config/lf/lfrc
  f_config.ini:
    src: config/polybar/config.ini
    dst: ~/.config/polybar/config.ini
profiles:
  hp:
    dotfiles:
    - f_profile
    - f_bashrc
    - f_xresources
    - f_picom.conf
    - f_autostart
    - f_bspwmrc
    - f_sxhkdrc
    - f_zshenv
    - f_zprofile
    - f_zshrc
    - f_aliases
    - f_gitconfig
    - f_clang-format
    - f_xinitrc
    - f_init.vim
    - f_plugins.vim
    - f_dmenu_run
    - f_update_edited
    - f_lfrc
    - f_config.ini
