config:
  backup: true
  banner: false
  create: true
  dotpath: .
  keepdot: false
  longkey: false
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  f_profile:
    src: profile
    dst: ~/.profile
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zprofile:
    src: config/zsh/.zprofile
    dst: ~/.config/zsh/.zprofile
  f_zshrc:
    src: config/zsh/.zshrc
    dst: ~/.config/zsh/.zshrc
  f_aliases:
    src: config/zsh/aliases
    dst: ~/.config/zsh/aliases
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_clang-format:
    src: clang-format
    dst: ~/.clang-format
  f_lfrc:
    src: config/lf/lfrc
    dst: ~/.config/lf/lfrc
  f_config:
    src: config/bat/config
    dst: ~/.config/bat/config
  f_fonts.conf:
    src: config/fontconfig/fonts.conf
    dst: ~/.config/fontconfig/fonts.conf
  f_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_gitsigns.lua:
    src: config/nvim/lua/config/gitsigns.lua
    dst: ~/.config/nvim/lua/config/gitsigns.lua
  f_lualine.lua:
    src: config/nvim/lua/config/lualine.lua
    dst: ~/.config/nvim/lua/config/lualine.lua
  f_augroups.lua:
    src: config/nvim/lua/augroups.lua
    dst: ~/.config/nvim/lua/augroups.lua
  f_keybindings.lua:
    src: config/nvim/lua/keybindings.lua
    dst: ~/.config/nvim/lua/keybindings.lua
  f_options.lua:
    src: config/nvim/lua/options.lua
    dst: ~/.config/nvim/lua/options.lua
  f_plugins.lua:
    src: config/nvim/lua/plugins.lua
    dst: ~/.config/nvim/lua/plugins.lua
  f_init.lua:
    src: config/nvim/init.lua
    dst: ~/.config/nvim/init.lua
  f_colors.lua:
    src: config/nvim/lua/config/colors.lua
    dst: ~/.config/nvim/lua/config/colors.lua
  f_indent_blankline.lua:
    src: config/nvim/lua/config/indent_blankline.lua
    dst: ~/.config/nvim/lua/config/indent_blankline.lua
  f_treesitter.lua:
    src: config/nvim/lua/config/treesitter.lua
    dst: ~/.config/nvim/lua/config/treesitter.lua
  f_telescope.lua:
    src: config/nvim/lua/config/telescope.lua
    dst: ~/.config/nvim/lua/config/telescope.lua
  f_cmp.lua:
    src: config/nvim/lua/config/cmp.lua
    dst: ~/.config/nvim/lua/config/cmp.lua
  f_lsp.lua:
    src: config/nvim/lua/config/lsp.lua
    dst: ~/.config/nvim/lua/config/lsp.lua
  f_rust_analyzer.lua:
    src: config/nvim/lua/config/lsp_settings/rust_analyzer.lua
    dst: ~/.config/nvim/lua/config/lsp_settings/rust_analyzer.lua
  f_lua_ls.lua:
    src: config/nvim/lua/config/lsp_settings/lua_ls.lua
    dst: ~/.config/nvim/lua/config/lsp_settings/lua_ls.lua
  f_taplo.lua:
    src: config/nvim/lua/config/lsp_settings/taplo.lua
    dst: ~/.config/nvim/lua/config/lsp_settings/taplo.lua
  f_null-ls.lua:
    src: config/nvim/lua/config/null-ls.lua
    dst: ~/.config/nvim/lua/config/null-ls.lua
  f_trouble.lua:
    src: config/nvim/lua/config/trouble.lua
    dst: ~/.config/nvim/lua/config/trouble.lua
  f_luasnip.lua:
    src: config/nvim/lua/config/luasnip.lua
    dst: ~/.config/nvim/lua/config/luasnip.lua
  f_stylua.toml:
    src: config/stylua/stylua.toml
    dst: ~/.config/stylua/stylua.toml
  f_toggleterm.lua:
    src: config/nvim/lua/config/toggleterm.lua
    dst: ~/.config/nvim/lua/config/toggleterm.lua
  f_dap.lua:
    src: config/nvim/lua/config/dap.lua
    dst: ~/.config/nvim/lua/config/dap.lua
  f_indent-o-matic.lua:
    src: config/nvim/lua/config/indent-o-matic.lua
    dst: ~/.config/nvim/lua/config/indent-o-matic.lua
  f_kanagawa.lua:
    src: config/nvim/lua/config/kanagawa.lua
    dst: ~/.config/nvim/lua/config/kanagawa.lua
  f_hyprland.conf:
    src: config/hypr/hyprland.conf
    dst: ~/.config/hypr/hyprland.conf
  f_config.jsonc:
    src: config/waybar/config.jsonc
    dst: ~/.config/waybar/config.jsonc
  f_style.css:
    src: config/waybar/style.css
    dst: ~/.config/waybar/style.css
profiles:
  arch:
    dotfiles:
      - f_profile
      - f_zshenv
      - f_zprofile
      - f_zshrc
      - f_aliases
      - f_gitconfig
      - f_clang-format
      - f_lfrc
      - f_config
      - f_fonts.conf
      - f_dunstrc
      - f_alacritty.yml
      - f_gitsigns.lua
      - f_lualine.lua
      - f_augroups.lua
      - f_keybindings.lua
      - f_options.lua
      - f_plugins.lua
      - f_init.lua
      - f_colors.lua
      - f_indent_blankline.lua
      - f_treesitter.lua
      - f_telescope.lua
      - f_cmp.lua
      - f_lsp.lua
      - f_rust_analyzer.lua
      - f_lua_ls.lua
      - f_taplo.lua
      - f_null-ls.lua
      - f_trouble.lua
      - f_luasnip.lua
      - f_stylua.toml
      - f_toggleterm.lua
      - f_dap.lua
      - f_indent-o-matic.lua
      - f_kanagawa.lua
      - f_hyprland.conf
      - f_config.jsonc
      - f_style.css
