config:
  backup: true
  banner: false
  create: true
  dotpath: .
  keepdot: false
  longkey: false
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_profile:
    src: profile
    dst: ~/.profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  f_autostart:
    src: config/bspwm/autostart
    dst: ~/.config/bspwm/autostart
  f_bspwmrc:
    src: config/bspwm/bspwmrc
    dst: ~/.config/bspwm/bspwmrc
  f_sxhkdrc:
    src: config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zprofile:
    src: config/zsh/.zprofile
    dst: ~/.config/zsh/.zprofile
  f_zshrc:
    src: config/zsh/.zshrc
    dst: ~/.config/zsh/.zshrc
  f_aliases:
    src: config/zsh/aliases
    dst: ~/.config/zsh/aliases
profiles:
  hp:
    dotfiles:
    - f_vimrc
    - f_profile
    - f_bashrc
    - f_xresources
    - f_picom.conf
    - f_autostart
    - f_bspwmrc
    - f_sxhkdrc
    - f_zshenv
    - f_zprofile
    - f_zshrc
    - f_aliases
