config:
  backup: true
  banner: false
  create: true
  dotpath: .
  keepdot: false
  longkey: false
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  f_profile:
    src: profile
    dst: ~/.profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  f_autostart:
    src: config/bspwm/autostart
    dst: ~/.config/bspwm/autostart
  f_sxhkdrc:
    src: config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zprofile:
    src: config/zsh/.zprofile
    dst: ~/.config/zsh/.zprofile
  f_zshrc:
    src: config/zsh/.zshrc
    dst: ~/.config/zsh/.zshrc
  f_aliases:
    src: config/zsh/aliases
    dst: ~/.config/zsh/aliases
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_clang-format:
    src: clang-format
    dst: ~/.clang-format
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_plugins.vim:
    src: config/nvim/vim-plug/plugins.vim
    dst: ~/.config/nvim/vim-plug/plugins.vim
  f_dmenu_colored:
    src: Documents/scripts/dmenu_colored
    dst: ~/Documents/scripts/dmenu_colored
  f_update_edited:
    src: Documents/scripts/update_edited
    dst: ~/Documents/scripts/update_edited
  f_lfrc:
    src: config/lf/lfrc
    dst: ~/.config/lf/lfrc
  f_config.ini:
    src: config/polybar/config.ini
    dst: ~/.config/polybar/config.ini
  f_modules.ini:
    src: config/polybar/modules.ini
    dst: ~/.config/polybar/modules.ini
  f_bspwm_resize:
    src: Documents/scripts/bspwm_resize
    dst: ~/Documents/scripts/bspwm_resize
  f_euclid_mover:
    src: Documents/scripts/euclid_mover
    dst: ~/Documents/scripts/euclid_mover
  f_wallpaper_changer:
    src: Documents/scripts/wallpaper_changer
    dst: ~/Documents/scripts/wallpaper_changer
  f_windowpromoter:
    src: Documents/scripts/windowpromoter
    dst: ~/Documents/scripts/windowpromoter
  f_dmenu_open_app:
    src: Documents/scripts/dmenu_open_app
    dst: ~/Documents/scripts/dmenu_open_app
  f_dmenu_open_site:
    src: Documents/scripts/dmenu_open_site
    dst: ~/Documents/scripts/dmenu_open_site
  f_dmenu_pacman:
    src: Documents/scripts/dmenu_pacman
    dst: ~/Documents/scripts/dmenu_pacman
  f_config:
    src: config/bat/config
    dst: ~/.config/bat/config
  f_fonts.conf:
    src: config/fontconfig/fonts.conf
    dst: ~/.config/fontconfig/fonts.conf
  f_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
profiles:
  arch:
    dotfiles:
    - f_profile
    - f_bashrc
    - f_xresources
    - f_picom.conf
    - f_autostart
    - f_sxhkdrc
    - f_zshenv
    - f_zprofile
    - f_zshrc
    - f_aliases
    - f_gitconfig
    - f_clang-format
    - f_xinitrc
    - f_init.vim
    - f_plugins.vim
    - f_dmenu_colored
    - f_update_edited
    - f_lfrc
    - f_config.ini
    - f_modules.ini
    - f_bspwm_resize
    - f_euclid_mover
    - f_wallpaper_changer
    - f_windowpromoter
    - f_dmenu_open_app
    - f_dmenu_open_site
    - f_dmenu_pacman
    - f_config
    - f_fonts.conf
    - f_dunstrc
    - f_coc-settings.json
