#!/bin/sh

wal -R && source ~/.config/polybar/launch.sh &
source ~/.fehbg &

xrdb -merge ~/.Xresources &

update_edited &
urxvtd -q &
picom -b &
sxhkd &
light -I &
fc-cache -f &
devmon &
dunst &
sleep 15 && dex -a &
light-locker &
