#!/bin/sh

wal -R && source ~/.config/polybar/launch.sh &
source ~/.fehbg &

xsetroot -cursor_name left_ptr &
export GTK2_RC_FILES="$HOME/.gtkrc-2.0" &
xrdb -merge ~/.Xresources &

update_edited &
picom -b &
sxhkd &
light -I &
fc-cache -fv &
devmon &
wallpaper_changer &

## powersaving options
xset s off &
xset s noblank &
xset s noexpose &
xset c on &
xset -dpms &

## Run screenlock when suspending
light-locker &

