#!/bin/bash

xrdb -merge ~/.Xresources &
source ~/.fehbg &

dunst &
light -I &
picom -b &
sxhkd &
thunar --daemon &
update_edited &
trash-empty 30 -f &

sleep 15 && dex -a &
fc-cache -f && wal -R && source ~/.config/polybar/launch.sh &
