#!/bin/sh
bspc rule -r "*"

source "$HOME/.config/bspwm/autostart" &
source "$HOME/.cache/wal/colors.sh"

export gap=15
export PANEL_HEIGHT=15

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap
bspc config top_padding $((-$PANEL_HEIGHT))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

setxkbmap -option grp:alt_shift_toggle us,ru
setxkbmap -option compose:ralt

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config single_monocle true
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true

# bspc config active_border_color "$color2"
# bspc config focused_border_color "$color15"
# bspc config normal_border_color "$color1"
bspc config presel_feedback_color "$color1"
bspc config border_width 1

bspc config focus_follows_pointer false
bspc config split_ratio         0.50

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a lxterminal state=floating center=true sticky=true
bspc rule -a viewnior state=floating center=true
bspc rule -a floaterm state=floating center=true
bspc rule -a conky sticky=on manage=off lower=on
bspc rule -a firefox private=on desktop=I follow=on
bspc rule -a Code private=on desktop=II
bspc rule -a wpa_gui state=pseudo_tiled
bspc rule -a Zathura state=tiled
